In [ ]:
import pandas as pd
import os
import json
def construct_df_full_data (json_path,  seed, rename_columns = None):
    folder = os.path.join(json_path, "full_data")
    file_scores = [file for file in os.listdir(folder) if f"best-seed{seed}" in file][0]

    json_file = open(os.path.join(folder, file_scores))
    json1_str = json_file.read()
    json1_data = json.loads(json1_str)
    clsuter_keys = set(json1_data.keys())
    print(len(clsuter_keys))
    df  = pd.DataFrame(json1_data).T
    if rename_columns is not None:
       mapping = { col: f"{col}_{rename_columns}_{seed}" for col in df.columns}
       df = df.rename(columns=mapping)
    return df

def construct_df_clsuter_data(json_path, seed, cluster_config, cluster_number,rename_columns= None):
    folder = os.path.join(json_path, cluster_config, f"{cluster_number}")
    print(folder)
    file_scores = [file for file in os.listdir(folder) if  file.startswith(f"best-seed{seed}")][0]   # f"best_checkpoint-seed{seed}" in file best_checkpoint-seed

    json_file = open(os.path.join(folder, file_scores))
    json1_str = json_file.read()
    json1_data = json.loads(json1_str)
    clsuter_keys = set(json1_data.keys())
    print(len(clsuter_keys))
    df  = pd.DataFrame(json1_data).T
    if rename_columns is not None:
       mapping = { col: f"{col}_{rename_columns}_{seed}" for col in df.columns}
       df = df.rename(columns=mapping)
    return df

In [ ]:
import json
import os
json_val_path = "json_val_scores/clusters4_layer12"
keys = {}
for i in range (1,5):
    folder = os.path.join(json_val_path, str(i))
    file_scores = [file for file in os.listdir(folder) if "best_checkpoint" in file][0]

    json_file = open(os.path.join(folder, file_scores))
    json1_str = json_file.read()
    json1_data = json.loads(json1_str)
    clsuter_keys = set(json1_data.keys())
    keys[i] = clsuter_keys
print(keys)

In [1]:
import pandas as pd
def construct_df_full_data (json_path,  seed, rename_columns = None):
    folder = os.path.join(json_path, "full_data")
    file_scores = [file for file in os.listdir(folder) if f"best-seed{seed}" in file][0]

    json_file = open(os.path.join(folder, file_scores))
    json1_str = json_file.read()
    json1_data = json.loads(json1_str)
    clsuter_keys = set(json1_data.keys())
    print(len(clsuter_keys))
    df  = pd.DataFrame(json1_data).T
    if rename_columns is not None:
       mapping = { col: f"{col}_{rename_columns}_{seed}" for col in df.columns}
       df = df.rename(columns=mapping)
    return df

In [2]:
def construct_df_clsuter_data(json_path, seed, cluster_config, cluster_number,rename_columns= None):
    folder = os.path.join(json_path, cluster_config, f"{cluster_number}")
    print(folder)
    file_scores = [file for file in os.listdir(folder) if  file.startswith(f"best-seed{seed}")][0]   # f"best_checkpoint-seed{seed}" in file best_checkpoint-seed

    json_file = open(os.path.join(folder, file_scores))
    json1_str = json_file.read()
    json1_data = json.loads(json1_str)
    clsuter_keys = set(json1_data.keys())
    print(len(clsuter_keys))
    df  = pd.DataFrame(json1_data).T
    if rename_columns is not None:
       mapping = { col: f"{col}_{rename_columns}_{seed}" for col in df.columns}
       df = df.rename(columns=mapping)
    return df

In [53]:
df1 = construct_df_clsuter_data(json_val_path, seed=0,cluster_config = "clusters2_layer6", cluster_number= 1,rename_columns= "clusters2_layer6")
df2 = construct_df_clsuter_data(json_val_path, seed=0,cluster_config = "clusters2_layer6", cluster_number= 2,rename_columns= "clusters2_layer6")
df_total = pd.concat([df1, df2], axis=0)
cols_f = [col for col in df_total.columns if "F-measure" in col]
df_total_f1 = df_total[cols_f]
df_total_f1 
means_total = (df_total.mean()* 100).to_dict()
means_total

347
209

{'F-measure_beat_clusters2_layer60': 92.87020670156396,
 'Cemgil_beat_clusters2_layer60': 85.10952250954362,
 'CMLt_beat_clusters2_layer60': 85.21058281061691,
 'AMLt_beat_clusters2_layer60': 89.36609345033831,
 'F-measure_downbeat_clusters2_layer60': 85.43487355624686,
 'Cemgil_downbeat_clusters2_layer60': 79.45757279218076,
 'CMLt_downbeat_clusters2_layer60': 72.77422067995289,
 'AMLt_downbeat_clusters2_layer60': 80.82696071845093}

In [54]:
df_full = construct_df_full_data (json_val_path, seed=0, rename_columns="baseline")
cols_f = [col for col in df_full.columns if "F-measure" in col]
df_fulll_f1 = df_full[cols_f]
means_full =(df_full.mean()*  100).to_dict()
means_full

556

{'F-measure_beat_baseline0': 92.67559037887163,
 'Cemgil_beat_baseline0': 84.89799383668344,
 'CMLt_beat_baseline0': 84.60569681054906,
 'AMLt_beat_baseline0': 88.71768403791125,
 'F-measure_downbeat_baseline0': 85.11133744115672,
 'Cemgil_downbeat_baseline0': 79.10203722776434,
 'CMLt_downbeat_baseline0': 72.10066458824532,
 'AMLt_downbeat_baseline0': 79.43592982857372}

In [55]:
diff_dict = {list(means_total.keys())[i]: means_total[list(means_total.keys())[i]] - means_full[list(means_full.keys())[i]] for i in range(len(means_full))}
diff_dict

{'F-measure_beat_clusters2_layer60': 0.1946163226923261,
 'Cemgil_beat_clusters2_layer60': 0.21152867286018306,
 'CMLt_beat_clusters2_layer60': 0.6048860000678502,
 'AMLt_beat_clusters2_layer60': 0.648409412427057,
 'F-measure_downbeat_clusters2_layer60': 0.32353611509013547,
 'Cemgil_downbeat_clusters2_layer60': 0.35553556441641376,
 'CMLt_downbeat_clusters2_layer60': 0.6735560917075674,
 'AMLt_downbeat_clusters2_layer60': 1.3910308898772143}

In [3]:
def construct_total_df (json_path, seed, cluster_config, cluster_numbers, rename_columns= None):
    df_list = []
    for cluster_number in cluster_numbers:
        df_cluster = construct_df_clsuter_data(json_path, seed, cluster_config, cluster_number, rename_columns= cluster_config)
        df_list.append (df_cluster)
    df_total = pd.concat(df_list, axis=0)
    df = df_total.groupby(df_total.index).mean()
    print(f"Final size of df is {len(df)}")

    return df

In [4]:
def get_performance_differences(df_total, df_full):
    means_total = (df_total.mean()* 100).to_dict()
    means_full =(df_full.mean()*  100).to_dict()
    diff_dict = {list(means_total.keys())[i]: means_total[list(means_total.keys())[i]] - means_full[list(means_full.keys())[i]] for i in range(len(means_full))}
    return diff_dict

In [85]:
df_total = construct_total_df (json_val_path, seed=0, cluster_config="clusters2_layer6", cluster_numbers=[1,2])
df_full = construct_df_full_data (json_val_path, seed=0, rename_columns="baseline")
diff_dict = get_performance_differences (df_total, df_full)
diff_dict

347
209
Final size of df is 556
556

{'F-measure_beat_clusters2_layer6_0': 0.19461632269238294,
 'Cemgil_beat_clusters2_layer6_0': 0.211528672860112,
 'CMLt_beat_clusters2_layer6_0': 0.6048860000678076,
 'AMLt_beat_clusters2_layer6_0': 0.6484094124270428,
 'F-measure_downbeat_clusters2_layer6_0': 0.3235361150901497,
 'Cemgil_downbeat_clusters2_layer6_0': 0.35553556441637113,
 'CMLt_downbeat_clusters2_layer6_0': 0.6735560917075816,
 'AMLt_downbeat_clusters2_layer6_0': 1.3910308898772996}

In [17]:
df_total = construct_total_df (json_val_path, seed=0, cluster_config="clusters4_layer12", cluster_numbers=[1,2, 3,4])
df_full = construct_df_full_data (json_val_path, seed=0, rename_columns="baseline")
diff_dict0 = get_performance_differences (df_total, df_full)
diff_dict0

json_val_scores/clusters4_layer12/1
220
json_val_scores/clusters4_layer12/2
123
json_val_scores/clusters4_layer12/3
153
json_val_scores/clusters4_layer12/4
106
Final size of df is 556
556

{'F-measure_beat_clusters4_layer12_0': 0.17011146854920867,
 'Cemgil_beat_clusters4_layer12_0': 0.21154820779605643,
 'CMLt_beat_clusters4_layer12_0': 0.6858410904917349,
 'AMLt_beat_clusters4_layer12_0': 0.5422025666788244,
 'F-measure_downbeat_clusters4_layer12_0': 0.2828661715811478,
 'Cemgil_downbeat_clusters4_layer12_0': 0.23577475631742573,
 'CMLt_downbeat_clusters4_layer12_0': 0.681876299303525,
 'AMLt_downbeat_clusters4_layer12_0': 0.9236112107499537}

In [7]:
#df0 = pd.DataFrame.from_dict(diff_dict0, orient='index', columns = ["Values0"])
df1= pd.DataFrame.from_dict(list(diff_dict1.items()), columns = ["Metric", "Value"] )
# df_res =  pd.concat([df0, df1], axis=0)
# df_res
df1

ValueError: cannot use columns parameter with orient='columns'

In [13]:
df1 = pd.DataFrame(list(diff_dict1.items()), columns=["Metric", "Value"])
df1

                                   Metric     Value
0      F-measure_beat_clusters4_layer12_1 -0.045774
1         Cemgil_beat_clusters4_layer12_1 -0.146955
2           CMLt_beat_clusters4_layer12_1 -0.323932
3           AMLt_beat_clusters4_layer12_1 -0.020322
4  F-measure_downbeat_clusters4_layer12_1  0.009791
5     Cemgil_downbeat_clusters4_layer12_1 -0.137542
6       CMLt_downbeat_clusters4_layer12_1 -0.178244
7       AMLt_downbeat_clusters4_layer12_1 -0.558642

In [14]:
diff_dict1.items()

dict_items([('F-measure_beat_clusters4_layer12_1', -0.04577390748724497), ('Cemgil_beat_clusters4_layer12_1', -0.1469553476583485), ('CMLt_beat_clusters4_layer12_1', -0.32393166924647687), ('AMLt_beat_clusters4_layer12_1', -0.020321947870471035), ('F-measure_downbeat_clusters4_layer12_1', 0.009791016016123422), ('Cemgil_downbeat_clusters4_layer12_1', -0.13754175909721766), ('CMLt_downbeat_clusters4_layer12_1', -0.17824391657016747), ('AMLt_downbeat_clusters4_layer12_1', -0.55864231428464)])

In [23]:
dict1_new = {}
for key in diff_dict1.keys():
    new_key = "_".join(key.split("_")[:-1])
    dict1_new [new_key] = diff_dict1[key]
dict1_new

{'F-measure_beat_clusters4_layer12': -0.04577390748724497,
 'Cemgil_beat_clusters4_layer12': -0.1469553476583485,
 'CMLt_beat_clusters4_layer12': -0.32393166924647687,
 'AMLt_beat_clusters4_layer12': -0.020321947870471035,
 'F-measure_downbeat_clusters4_layer12': 0.009791016016123422,
 'Cemgil_downbeat_clusters4_layer12': -0.13754175909721766,
 'CMLt_downbeat_clusters4_layer12': -0.17824391657016747,
 'AMLt_downbeat_clusters4_layer12': -0.55864231428464}

In [20]:
import os
import json
json_val_path = "json_val_scores"
df_total = construct_total_df (json_val_path, seed=1, cluster_config="clusters4_layer12", cluster_numbers=[1,2, 3,4])
df_full = construct_df_full_data (json_val_path, seed=1, rename_columns="baseline")
diff_dict1 = get_performance_differences (df_total, df_full)
diff_dict1

json_val_scores/clusters4_layer12/1
220
json_val_scores/clusters4_layer12/2
123
json_val_scores/clusters4_layer12/3
153
json_val_scores/clusters4_layer12/4
106
Final size of df is 556
556

{'F-measure_beat_clusters4_layer12_1': -0.04577390748724497,
 'Cemgil_beat_clusters4_layer12_1': -0.1469553476583485,
 'CMLt_beat_clusters4_layer12_1': -0.32393166924647687,
 'AMLt_beat_clusters4_layer12_1': -0.020321947870471035,
 'F-measure_downbeat_clusters4_layer12_1': 0.009791016016123422,
 'Cemgil_downbeat_clusters4_layer12_1': -0.13754175909721766,
 'CMLt_downbeat_clusters4_layer12_1': -0.17824391657016747,
 'AMLt_downbeat_clusters4_layer12_1': -0.55864231428464}

In [42]:
def rename_keys_dict(d):
    dict_new = {}
    for key in d.keys():
        new_key = "_".join(key.split("_")[:-1])
        dict_new [new_key] = d[key]
    return dict_new
def get_total_results (seeds, json_val_path, cluster_config, cluster_numbers):
    df_list = []
    for seed in seeds:
        df_total = construct_total_df (json_val_path, seed=seed, cluster_config=cluster_config, cluster_numbers=cluster_numbers)
        df_full = construct_df_full_data (json_val_path, seed=seed, rename_columns="baseline")
        diff_dict = get_performance_differences (df_total, df_full)
        diff_dict_renamed = rename_keys_dict(diff_dict)
        #print(diff_dict_renamed)
        df = pd.DataFrame.from_dict(diff_dict_renamed, orient="index", columns=[f"Value_{seed}"])
        #df.index.name = "Metric"
        df_list.append(df)
    df_result =  pd.concat(df_list, axis=1)
    return df_result

In [45]:
df_total = get_total_results (seeds = [0,1], json_val_path = "json_val_scores", cluster_config="clusters4_layer12", cluster_numbers=[1,2, 3,4])
df_total.mean(axis = 1)
df_total

json_val_scores/clusters4_layer12/1
220
json_val_scores/clusters4_layer12/2
123
json_val_scores/clusters4_layer12/3
153
json_val_scores/clusters4_layer12/4
106
Final size of df is 556
556
json_val_scores/clusters4_layer12/1
220
json_val_scores/clusters4_layer12/2
123
json_val_scores/clusters4_layer12/3
153
json_val_scores/clusters4_layer12/4
106
Final size of df is 556
556

                                       Value_0   Value_1
F-measure_beat_clusters4_layer12      0.170111 -0.045774
Cemgil_beat_clusters4_layer12         0.211548 -0.146955
CMLt_beat_clusters4_layer12           0.685841 -0.323932
AMLt_beat_clusters4_layer12           0.542203 -0.020322
F-measure_downbeat_clusters4_layer12  0.282866  0.009791
Cemgil_downbeat_clusters4_layer12     0.235775 -0.137542
CMLt_downbeat_clusters4_layer12       0.681876 -0.178244
AMLt_downbeat_clusters4_layer12       0.923611 -0.558642

In [21]:
import os
import json
json_val_path = "json_val_scores"
df_total = construct_total_df (json_val_path, seed=0, cluster_config="clusters3_layer113", cluster_numbers=[1,2, 3])
df_full = construct_df_full_data (json_val_path, seed=0, rename_columns="baseline")
diff_dict = get_performance_differences (df_total, df_full)
diff_dict

json_val_scores/clusters3_layer113/1
184
json_val_scores/clusters3_layer113/2
204
json_val_scores/clusters3_layer113/3
168
Final size of df is 556
556

{'F-measure_beat_clusters3_layer113_0': -0.009816996519390386,
 'Cemgil_beat_clusters3_layer113_0': -0.23713233829714397,
 'CMLt_beat_clusters3_layer113_0': 0.19418560072544722,
 'AMLt_beat_clusters3_layer113_0': 0.03538814802558932,
 'F-measure_downbeat_clusters3_layer113_0': 0.20640883754387573,
 'Cemgil_downbeat_clusters3_layer113_0': -0.14219493196397082,
 'CMLt_downbeat_clusters3_layer113_0': 0.4797200504718404,
 'AMLt_downbeat_clusters3_layer113_0': 0.33998351550118855}

In [ ]:
df_total.isna()

,F-measure_beat_clusters3_layer113_0,Cemgil_beat_clusters3_layer113_0,CMLt_beat_clusters3_layer113_0,AMLt_beat_clusters3_layer113_0,F-measure_downbeat_clusters3_layer113_0,Cemgil_downbeat_clusters3_layer113_0,CMLt_downbeat_clusters3_layer113_0,AMLt_downbeat_clusters3_layer113_0
asap/Bach_Fugue_bwv_873_Lisiecki13M/track.npy,False,False,False,False,False,False,False,False
asap/Bach_Fugue_bwv_874_BianF01/track.npy,False,False,False,False,False,False,False,False
asap/Bach_Fugue_bwv_874_Kurz01M/track.npy,False,False,False,False,False,False,False,False
asap/Bach_Fugue_bwv_874_WongWY01M/track.npy,False,False,False,False,False,False,False,False
asap/Bach_Fugue_bwv_875_Ahfat01M/track.npy,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...
tapcorrect/066_youtube_H4BB9eGUEaE/track.npy,False,False,False,False,False,False,False,False
tapcorrect/069_youtube_8kl6q_9qZOs/track.npy,False,False,False,False,False,False,False,False
tapcorrect/087_youtube_ej93qIAlhXs/track.npy,False,False,False,False,False,False,False,False
tapcorrect/093_youtube_C1lbOgBtE3w/track.npy,False,False,False,False,False,False,False,False
tapcorrect/097_youtube_Nco69szMp0Y/track.npy,False,False,False,False,False,False,False,False

In [70]:
df2

,F-measure_beat_clusters4_layer120,Cemgil_beat_clusters4_layer120,CMLt_beat_clusters4_layer120,AMLt_beat_clusters4_layer120,F-measure_downbeat_clusters4_layer120,Cemgil_downbeat_clusters4_layer120,CMLt_downbeat_clusters4_layer120,AMLt_downbeat_clusters4_layer120
ballroom/ballroom_Albums-Cafe_Paradiso-01/track.npy,1.000000,0.922979,1.000000,1.000000,1.000000,0.896015,1.000000,1.000000
ballroom/ballroom_Albums-Cafe_Paradiso-07/track.npy,1.000000,0.974899,1.000000,1.000000,1.000000,0.995267,1.000000,1.000000
ballroom/ballroom_Albums-Cafe_Paradiso-12/track.npy,1.000000,0.954732,1.000000,1.000000,0.952381,0.898297,0.909091,0.909091
ballroom/ballroom_Albums-Commitments-08/track.npy,0.971014,0.947054,0.929577,0.929577,0.969697,0.937109,0.941176,0.941176
ballroom/ballroom_Albums-Commitments-11/track.npy,1.000000,0.936685,1.000000,1.000000,1.000000,0.952677,1.000000,1.000000
...,...,...,...,...,...,...,...,...
tapcorrect/045_youtube_SYUgGs9IStY/track.npy,0.781570,0.776370,0.280112,0.562363,0.642857,0.704612,0.052632,0.684211
tapcorrect/066_youtube_H4BB9eGUEaE/track.npy,1.000000,0.951452,1.000000,1.000000,0.862500,0.831361,0.627907,0.627907
tapcorrect/069_youtube_8kl6q_9qZOs/track.npy,0.963438,0.876585,0.930521,0.930521,0.949495,0.847326,0.908213,0.908213
tapcorrect/087_youtube_ej93qIAlhXs/track.npy,0.996870,0.965523,0.993760,0.993760,0.996865,0.958880,0.993750,0.993750
tapcorrect/093_youtube_C1lbOgBtE3w/track.npy,0.902944,0.836854,0.663347,0.663347,0.759124,0.772878,0.223529,0.632850

In [73]:
len(set(df1.index)  & set(df2.index))

28

In [67]:
idncies_repeat = [ind for ind in df_total.index.to_list() if df_total.index.to_list().count(ind) >1]
len(idncies_repeat)

56

In [11]:
mapping

{'F-measure_beat_full_data_seed0': 'F-measure_beat',
 'Cemgil_beat_full_data_seed0': 'Cemgil_beat',
 'CMLt_beat_full_data_seed0': 'CMLt_beat',
 'AMLt_beat_full_data_seed0': 'AMLt_beat',
 'F-measure_downbeat_full_data_seed0': 'F-measure_downbeat',
 'Cemgil_downbeat_full_data_seed0': 'Cemgil_downbeat',
 'CMLt_downbeat_full_data_seed0': 'CMLt_downbeat',
 'AMLt_downbeat_full_data_seed0': 'AMLt_downbeat'}

In [12]:
seed = 0
mapping = { col: f"{col}_full_data_seed{seed}" for col in df.columns}
df = df.rename(columns=mapping)
df

,F-measure_beat_full_data_seed0,Cemgil_beat_full_data_seed0,CMLt_beat_full_data_seed0,AMLt_beat_full_data_seed0,F-measure_downbeat_full_data_seed0,Cemgil_downbeat_full_data_seed0,CMLt_downbeat_full_data_seed0,AMLt_downbeat_full_data_seed0
asap/Bach_Fugue_bwv_873_Lisiecki13M/track.npy,0.990689,0.946179,0.977695,0.977695,0.554545,0.619217,0.045752,0.437908
asap/Bach_Fugue_bwv_874_BianF01/track.npy,0.103806,0.089323,0.000000,0.606218,0.040201,0.036285,0.000000,0.000000
asap/Bach_Fugue_bwv_874_Kurz01M/track.npy,0.666667,0.768584,0.000000,0.984536,0.571429,0.662933,0.000000,0.600000
asap/Bach_Fugue_bwv_874_WongWY01M/track.npy,0.664384,0.763135,0.000000,0.969231,0.548780,0.627003,0.000000,0.586207
asap/Bach_Fugue_bwv_875_Ahfat01M/track.npy,0.736842,0.717897,0.361111,0.385366,0.355932,0.387693,0.000000,0.173913
...,...,...,...,...,...,...,...,...
tapcorrect/066_youtube_H4BB9eGUEaE/track.npy,1.000000,0.952138,1.000000,1.000000,0.867925,0.831172,0.647059,0.647059
tapcorrect/069_youtube_8kl6q_9qZOs/track.npy,0.960358,0.864980,0.924784,0.924784,0.930693,0.827054,0.874419,0.874419
tapcorrect/087_youtube_ej93qIAlhXs/track.npy,0.996870,0.969499,0.993760,0.993760,0.996865,0.965355,0.993750,0.993750
tapcorrect/093_youtube_C1lbOgBtE3w/track.npy,0.909890,0.838151,0.690909,0.690909,0.803089,0.766750,0.348387,0.478261
tapcorrect/097_youtube_Nco69szMp0Y/track.npy,0.872038,0.792702,0.575372,0.575372,0.778243,0.735967,0.296552,0.545455

In [7]:
import json
import os
import pandas as pd
json_val_path = "json_val_scores"
keys = {}

folder = os.path.join(json_val_path, "full_data")
file_scores = [file for file in os.listdir(folder) if "best-seed0" in file][0]

json_file = open(os.path.join(folder, file_scores))
json1_str = json_file.read()
json1_data = json.loads(json1_str)
clsuter_keys = set(json1_data.keys())
print(len(clsuter_keys))
df  = pd.DataFrame(json1_data).T
df

556

,F-measure_beat,Cemgil_beat,CMLt_beat,AMLt_beat,F-measure_downbeat,Cemgil_downbeat,CMLt_downbeat,AMLt_downbeat
asap/Bach_Fugue_bwv_873_Lisiecki13M/track.npy,0.990689,0.946179,0.977695,0.977695,0.554545,0.619217,0.045752,0.437908
asap/Bach_Fugue_bwv_874_BianF01/track.npy,0.103806,0.089323,0.000000,0.606218,0.040201,0.036285,0.000000,0.000000
asap/Bach_Fugue_bwv_874_Kurz01M/track.npy,0.666667,0.768584,0.000000,0.984536,0.571429,0.662933,0.000000,0.600000
asap/Bach_Fugue_bwv_874_WongWY01M/track.npy,0.664384,0.763135,0.000000,0.969231,0.548780,0.627003,0.000000,0.586207
asap/Bach_Fugue_bwv_875_Ahfat01M/track.npy,0.736842,0.717897,0.361111,0.385366,0.355932,0.387693,0.000000,0.173913
...,...,...,...,...,...,...,...,...
tapcorrect/066_youtube_H4BB9eGUEaE/track.npy,1.000000,0.952138,1.000000,1.000000,0.867925,0.831172,0.647059,0.647059
tapcorrect/069_youtube_8kl6q_9qZOs/track.npy,0.960358,0.864980,0.924784,0.924784,0.930693,0.827054,0.874419,0.874419
tapcorrect/087_youtube_ej93qIAlhXs/track.npy,0.996870,0.969499,0.993760,0.993760,0.996865,0.965355,0.993750,0.993750
tapcorrect/093_youtube_C1lbOgBtE3w/track.npy,0.909890,0.838151,0.690909,0.690909,0.803089,0.766750,0.348387,0.478261
tapcorrect/097_youtube_Nco69szMp0Y/track.npy,0.872038,0.792702,0.575372,0.575372,0.778243,0.735967,0.296552,0.545455

In [6]:
json1_data

{'asap/Bach_Fugue_bwv_873_Lisiecki13M/track.npy': {'F-measure_beat': 0.9906890130353817,
  'Cemgil_beat': 0.9461791100978764,
  'CMLt_beat': 0.9776951672862454,
  'AMLt_beat': 0.9776951672862454,
  'F-measure_downbeat': 0.5545454545454546,
  'Cemgil_downbeat': 0.6192171586932619,
  'CMLt_downbeat': 0.0457516339869281,
  'AMLt_downbeat': 0.43790849673202614},
 'asap/Bach_Fugue_bwv_874_BianF01/track.npy': {'F-measure_beat': 0.10380622837370242,
  'Cemgil_beat': 0.08932329235123523,
  'CMLt_beat': 0.0,
  'AMLt_beat': 0.6062176165803109,
  'F-measure_downbeat': 0.04020100502512563,
  'Cemgil_downbeat': 0.03628480207402904,
  'CMLt_downbeat': 0.0,
  'AMLt_downbeat': 0.0},
 'asap/Bach_Fugue_bwv_874_Kurz01M/track.npy': {'F-measure_beat': 0.6666666666666666,
  'Cemgil_beat': 0.7685835752035493,
  'CMLt_beat': 0.0,
  'AMLt_beat': 0.9845360824742269,
  'F-measure_downbeat': 0.5714285714285715,
  'Cemgil_downbeat': 0.6629334122797284,
  'CMLt_downbeat': 0.0,
  'AMLt_downbeat': 0.6},
 'asap/Bach_Fugue_bwv_874_WongWY01M/track.npy': {'F-measure_beat': 0.6643835616438356,
  'Cemgil_beat': 0.7631349784093933,
  'CMLt_beat': 0.0,
  'AMLt_beat': 0.9692307692307692,
  'F-measure_downbeat': 0.548780487804878,
  'Cemgil_downbeat': 0.6270025796599158,
  'CMLt_downbeat': 0.0,
  'AMLt_downbeat': 0.5862068965517241},
 'asap/Bach_Fugue_bwv_875_Ahfat01M/track.npy': {'F-measure_beat': 0.736842105263158,
  'Cemgil_beat': 0.7178966516604872,
  'CMLt_beat': 0.3611111111111111,
  'AMLt_beat': 0.3853658536585366,
  'F-measure_downbeat': 0.3559322033898305,
  'Cemgil_downbeat': 0.3876927983340421,
  'CMLt_downbeat': 0.0,
  'AMLt_downbeat': 0.17391304347826086},
 'asap/Bach_Fugue_bwv_875_CaoJ01M/track.npy': {'F-measure_beat': 0.9383886255924171,
  'Cemgil_beat': 0.9036908866425527,
  'CMLt_beat': 0.8073394495412844,
  'AMLt_beat': 0.8073394495412844,
  'F-measure_downbeat': 0.48076923076923084,
  'Cemgil_downbeat': 0.5675445701057537,
  'CMLt_downbeat': 0.0,
  'AMLt_downbeat': 0.2911392405063291},
 'asap/Bach_Fugue_bwv_883_GuoE01M/track.npy': {'F-measure_beat': 0.9855072463768115,
  'Cemgil_beat': 0.9251608248689337,
  'CMLt_beat': 0.9678571428571429,
  'AMLt_beat': 0.9678571428571429,
  'F-measure_downbeat': 0.466403162055336,
  'Cemgil_downbeat': 0.5457104652410262,
  'CMLt_downbeat': 0.0,
  'AMLt_downbeat': 0.3837837837837838},
 'asap/Bach_Fugue_bwv_883_Herbert02/track.npy': {'F-measure_beat': 0.007366482504604052,
  'Cemgil_beat': 0.011242009684030262,
  'CMLt_beat': 0.30514705882352944,
  'AMLt_beat': 0.30514705882352944,
  'F-measure_downbeat': 0.0,
  'Cemgil_downbeat': 0.0051588820614070574,
  'CMLt_downbeat': 0.0,
  'AMLt_downbeat': 0.14285714285714285},
 'asap/Bach_Fugue_bwv_883_KaiRuiR03/track.npy': {'F-measure_beat': 0.014732965009208104,
  'Cemgil_beat': 0.1282978440855586,
  'CMLt_beat': 0.029411764705882353,
  'AMLt_beat': 0.6346863468634686,
  'F-measure_downbeat': 0.0,
  'Cemgil_downbeat': 0.0026283174580686505,
  'CMLt_downbeat': 0.0,
  'AMLt_downbeat': 0.17682926829268292},
 'asap/Bach_Fugue_bwv_883_Khmara04/track.npy': {'F-measure_beat': 0.0036496350364963502,
  'Cemgil_beat': 0.0018470353879239784,
  'CMLt_beat': 0.0,
  'AMLt_beat': 0.2690909090909091,
  'F-measure_downbeat': 0.0,
  'Cemgil_downbeat': 3.384033567759096e-08,
  'CMLt_downbeat': 0.0,
  'AMLt_downbeat': 0.0783132530120482},
 'asap/Bach_Fugue_bwv_883_LuM01M/track.npy': {'F-measure_beat': 0.990791896869245,
  'Cemgil_beat': 0.9268490425536806,
  'CMLt_beat': 0.9926470588235294,
  'AMLt_beat': 0.9926470588235294,
  'F-measure_downbeat': 0.467741935483871,
  'Cemgil_downbeat': 0.5274413196881585,
  'CMLt_downbeat': 0.016666666666666666,
  'AMLt_downbeat': 0.3111111111111111},
 'asap/Bach_Fugue_bwv_885_Guo01M/track.npy': {'F-measure_beat': 0.9775967413441955,
  'Cemgil_beat': 0.9384019205939386,
  'CMLt_beat': 0.927710843373494,
  'AMLt_beat': 0.927710843373494,
  'F-measure_downbeat': 0.4954128440366973,
  'Cemgil_downbeat': 0.4778414475204427,
  'CMLt_downbeat': 0.1386861313868613,
  'AMLt_downbeat': 0.1386861313868613},
 'asap/Bach_Fugue_bwv_885_Huang04M/track.npy': {'F-measure_beat': 0.983739837398374,
  'Cemgil_beat': 0.9471731585449321,
  'CMLt_beat': 0.9477911646586346,
  'AMLt_beat': 0.9477911646586346,
  'F-measure_downbeat': 0.5161290322580644,
  'Cemgil_downbeat': 0.49912189265740037,
  'CMLt_downbeat': 0.010101010101010102,
  'AMLt_downbeat': 0.010101010101010102},
 'asap/Bach_Fugue_bwv_885_JeonH01M/track.npy': {'F-measure_beat': 0.9302325581395349,
  'Cemgil_beat': 0.8954846456433213,
  'CMLt_beat': 0.76,
  'AMLt_beat': 0.76,
  'F-measure_downbeat': 0.4415584415584416,
  'Cemgil_downbeat': 0.427172591880823,
  'CMLt_downbeat': 0.09333333333333334,
  'AMLt_downbeat': 0.09333333333333334},
 'asap/Bach_Fugue_bwv_885_SINKEV06/track.npy': {'F-measure_beat': 0.08610567514677103,
  'Cemgil_beat': 0.08150678983030266,
  'CMLt_beat': 0.3148148148148148,
  'AMLt_beat': 0.3148148148148148,
  'F-measure_downbeat': 0.04651162790697674,
  'Cemgil_downbeat': 0.04491871227671072,
  'CMLt_downbeat': 0.09701492537313433,
  'AMLt_downbeat': 0.09701492537313433},
 'asap/Bach_Prelude_bwv_857_Bult-ItoS02M/track.npy': {'F-measure_beat': 1.0,
  'Cemgil_beat': 0.948772442588776,
  'CMLt_beat': 1.0,
  'AMLt_beat': 1.0,
  'F-measure_downbeat': 0.576271186440678,
  'Cemgil_downbeat': 0.5678297792564269,
  'CMLt_downbeat': 0.0,
  'AMLt_downbeat': 0.7560975609756098},
 'asap/Bach_Prelude_bwv_857_Lan01M/track.npy': {'F-measure_beat': 0.9938650306748467,
  'Cemgil_beat': 0.9206816365158084,
  'CMLt_beat': 0.9878048780487805,
  'AMLt_beat': 0.9878048780487805,
  'F-measure_downbeat': 0.5405405405405405,
  'Cemgil_downbeat': 0.5686335252540499,
  'CMLt_downbeat': 0.0,
  'AMLt_downbeat': 0.5094339622641509},
 'asap/Bach_Prelude_bwv_857_Lisiecki04M/track.npy': {'F-measure_beat': 0.9820359281437125,
  'Cemgil_beat': 0.9326102410710307,
  'CMLt_beat': 0.9294117647058824,
  'AMLt_beat': 0.9294117647058824,
  'F-measure_downbeat': 0.5757575757575758,
  'Cemgil_downbeat': 0.5785400285982396,
  'CMLt_downbeat': 0.0,
  'AMLt_downbeat': 0.6444444444444445},
 'asap/Bach_Prelude_bwv_857_ToA01M/track.npy': {'F-measure_beat': 0.9585798816568047,
  'Cemgil_beat': 0.9109724831862618,
  'CMLt_beat': 0.8735632183908046,
  'AMLt_beat': 0.8735632183908046,
  'F-measure_downbeat': 0.5675675675675675,
  'Cemgil_downbeat': 0.5803837192666402,
  'CMLt_downbeat': 0.0,
  'AMLt_downbeat': 0.5660377358490566},
 'asap/Bach_Prelude_bwv_857_WangA01M/track.npy': {'F-measure_beat': 0.9050279329608938,
  'Cemgil_beat': 0.8631846015912445,
  'CMLt_beat': 0.6907216494845361,
  'AMLt_beat': 0.6907216494845361,
  'F-measure_downbeat': 0.4878048780487805,
  'Cemgil_downbeat': 0.5399447107862592,
  'CMLt_downbeat': 0.0,
  'AMLt_downbeat': 0.36065573770491804},
 'asap/Bach_Prelude_bwv_857_YuP01M/track.npy': {'F-measure_beat': 1.0,
  'Cemgil_beat': 0.9377318208291155,
  'CMLt_beat': 1.0,
  'AMLt_beat': 1.0,
  'F-measure_downbeat': 0.6,
  'Cemgil_downbeat': 0.5897145243281181,
  'CMLt_downbeat': 0.0,
  'AMLt_downbeat': 0.673469387755102},
 'asap/Bach_Prelude_bwv_864_SunD01M/track.npy': {'F-measure_beat': 0.7239819004524886,
  'Cemgil_beat': 0.7351252844215072,
  'CMLt_beat': 0.2781954887218045,
  'AMLt_beat': 0.4685714285714286,
  'F-measure_downbeat': 0.30588235294117644,
  'Cemgil_downbeat': 0.4043417498702666,
  'CMLt_downbeat': 0.0,
  'AMLt_downbeat': 0.1746031746031746},
 'asap/Bach_Prelude_bwv_865_Rizikov01M/track.npy': {'F-measure_beat': 0.9934640522875817,
  'Cemgil_beat': 0.9577950972986248,
  'CMLt_beat': 0.974025974025974,
  'AMLt_beat': 0.974025974025974,
  'F-measure_downbeat': 0.5517241379310345,
  'Cemgil_downbeat': 0.5225843793685955,
  'CMLt_downbeat': 0.01639344262295082,
  'AMLt_downbeat': 0.01639344262295082},
 'asap/Bach_Prelude_bwv_865_Teo01M/track.npy': {'F-measure_beat': 0.6339285714285714,
  'Cemgil_beat': 0.5693150655509315,
  'CMLt_beat': 0.11409395973154363,
  'AMLt_beat': 0.11409395973154363,
  'F-measure_downbeat': 0.38333333333333336,
  'Cemgil_downbeat': 0.34764368833553133,
  'CMLt_downbeat': 0.0,
  'AMLt_downbeat': 0.031578947368421054},
 'asap/Bach_Prelude_bwv_865_ZhangE01M/track.npy': {'F-measure_beat': 0.9268292682926829,
  'Cemgil_beat': 0.8864883880780147,
  'CMLt_beat': 0.7386363636363636,
  'AMLt_beat': 0.7386363636363636,
  'F-measure_downbeat': 0.5098039215686275,
  'Cemgil_downbeat': 0.4838555649585334,
  'CMLt_downbeat': 0.0,
  'AMLt_downbeat': 0.013157894736842105},
 'asap/Bach_Prelude_bwv_867_HuNY01M/track.npy': {'F-measure_beat': 0.9523809523809524,
  'Cemgil_beat': 0.9241697969929521,
  'CMLt_beat': 0.865979381443299,
  'AMLt_beat': 0.865979381443299,
  'F-measure_downbeat': 0.47191011235955055,
  'Cemgil_downbeat': 0.4609473561835737,
  'CMLt_downbeat': 0.0,
  'AMLt_downbeat': 0.30303030303030304},
 'asap/Bach_Prelude_bwv_867_Sham01M/track.npy': {'F-measure_beat': 0.892156862745098,
  'Cemgil_beat': 0.8507545232754822,
  'CMLt_beat': 0.6160714285714286,
  'AMLt_beat': 0.6160714285714286,
  'F-measure_downbeat': 0.4597701149425288,
  'Cemgil_downbeat': 0.49668134710871314,
  'CMLt_downbeat': 0.0,
  'AMLt_downbeat': 0.390625},
 'asap/Bach_Prelude_bwv_875_Ahfat01M/track.npy': {'F-measure_beat': 0.8360655737704918,
  'Cemgil_beat': 0.7932901410343578,
  'CMLt_beat': 0.5948717948717949,
  'AMLt_beat': 0.5948717948717949,
  'F-measure_downbeat': 0.8421052631578947,
  'Cemgil_downbeat': 0.8113149381647903,
  'CMLt_downbeat': 0.4868421052631579,
  'AMLt_downbeat': 0.4868421052631579},
 'asap/Bach_Prelude_bwv_875_CaoJ01M/track.npy': {'F-measure_beat': 0.8047619047619048,
  'Cemgil_beat': 0.7707122618867498,
  'CMLt_beat': 0.375,
  'AMLt_beat': 0.375,
  'F-measure_downbeat': 0.8260869565217391,
  'Cemgil_downbeat': 0.7925740964852964,
  'CMLt_downbeat': 0.45,
  'AMLt_downbeat': 0.45},
 'asap/Bach_Prelude_bwv_875_HONG04M/track.npy': {'F-measure_beat': 0.8415584415584416,
  'Cemgil_beat': 0.7931562820731497,
  'CMLt_beat': 0.5258215962441315,
  'AMLt_beat': 0.5258215962441315,
  'F-measure_downbeat': 0.8750000000000001,
  'Cemgil_downbeat': 0.8296517430256597,
  'CMLt_downbeat': 0.6,
  'AMLt_downbeat': 0.6},
 'asap/Balakirev_Islamey_CHEN10M/track.npy': {'F-measure_beat': 0.7475130270014212,
  'Cemgil_beat': 0.5944665894289856,
  'CMLt_beat': 0.466728280961183,
  'AMLt_beat': 0.466728280961183,
  'F-measure_downbeat': 0.6234067207415991,
  'Cemgil_downbeat': 0.5033852963414233,
  'CMLt_downbeat': 0.3231357552581262,
  'AMLt_downbeat': 0.3231357552581262},
 'asap/Balakirev_Islamey_Na08M/track.npy': {'F-measure_beat': 0.7099447513812155,
  'Cemgil_beat': 0.5564874004253646,
  'CMLt_beat': 0.3481675392670157,
  'AMLt_beat': 0.3481675392670157,
  'F-measure_downbeat': 0.5412748171368861,
  'Cemgil_downbeat': 0.4452358189686011,
  'CMLt_downbeat': 0.23462783171521034,
  'AMLt_downbeat': 0.23462783171521034},
 'asap/Balakirev_Islamey_Yi04M/track.npy': {'F-measure_beat': 0.7887323943661971,
  'Cemgil_beat': 0.6638308845740293,
  'CMLt_beat': 0.5395814376706096,
  'AMLt_beat': 0.5395814376706096,
  'F-measure_downbeat': 0.549520766773163,
  'Cemgil_downbeat': 0.45816338747066515,
  'CMLt_downbeat': 0.17195325542570952,
  'AMLt_downbeat': 0.18409425625920472},
 'asap/Beethoven_Piano_Sonatas_24-2_Lisiecki05M/track.npy': {'F-measure_beat': 0.6205571565802113,
  'Cemgil_beat': 0.535968876033706,
  'CMLt_beat': 0.10319767441860465,
  'AMLt_beat': 0.3120567375886525,
  'F-measure_downbeat': 0.6373626373626373,
  'Cemgil_downbeat': 0.5303197007054189,
  'CMLt_downbeat': 0.34172661870503596,
  'AMLt_downbeat': 0.34172661870503596},
 'asap/Beethoven_Piano_Sonatas_4-1_Chon03M/track.npy': {'F-measure_beat': 0.8314899154196488,
  'Cemgil_beat': 0.745881752387509,
  'CMLt_beat': 0.6755447941888619,
  'AMLt_beat': 0.6755447941888619,
  'F-measure_downbeat': 0.6638054363376252,
  'Cemgil_downbeat': 0.5972255912095871,
  'CMLt_downbeat': 0.4157303370786517,
  'AMLt_downbeat': 0.4157303370786517},
 'asap/Beethoven_Piano_Sonatas_4-1_LeeE02M/track.npy': {'F-measure_beat': 0.8445563247325362,
  'Cemgil_beat': 0.7941239973167107,
  'CMLt_beat': 0.60250569476082,
  'AMLt_beat': 0.60250569476082,
  'F-measure_downbeat': 0.7058823529411764,
  'Cemgil_downbeat': 0.6789083473608689,
  'CMLt_downbeat': 0.44662921348314605,
  'AMLt_downbeat': 0.44662921348314605},
 'asap/Beethoven_Piano_Sonatas_4-1_LiA04M/track.npy': {'F-measure_beat': 0.8458093410108766,
  'Cemgil_beat': 0.7867033515681965,
  'CMLt_beat': 0.6396713615023474,
  'AMLt_beat': 0.6396713615023474,
  'F-measure_downbeat': 0.6390532544378699,
  'Cemgil_downbeat': 0.6027414433493591,
  'CMLt_downbeat': 0.29213483146067415,
  'AMLt_downbeat': 0.29213483146067415},
 'asap/Beethoven_Piano_Sonatas_4-1_SirajA02M/track.npy': {'F-measure_beat': 0.852604828462516,
  'Cemgil_beat': 0.7857003600691244,
  'CMLt_beat': 0.642691415313225,
  'AMLt_beat': 0.642691415313225,
  'F-measure_downbeat': 0.6549707602339182,
  'Cemgil_downbeat': 0.6133545632922811,
  'CMLt_downbeat': 0.3651685393258427,
  'AMLt_downbeat': 0.3651685393258427},
 'asap/Chopin_Ballades_4_ChenC04M/track.npy': {'F-measure_beat': 0.6392067124332571,
  'Cemgil_beat': 0.549590632150253,
  'CMLt_beat': 0.3140794223826715,
  'AMLt_beat': 0.3140794223826715,
  'F-measure_downbeat': 0.5246422893481716,
  'Cemgil_downbeat': 0.45383748631109316,
  'CMLt_downbeat': 0.18766066838046272,
  'AMLt_downbeat': 0.2755741127348643},
 'asap/Chopin_Ballades_4_Kociuban07M/track.npy': {'F-measure_beat': 0.6235119047619048,
  'Cemgil_beat': 0.523233345350399,
  'CMLt_beat': 0.3082271147161066,
  'AMLt_beat': 0.3082271147161066,
  'F-measure_downbeat': 0.5148809523809524,
  'Cemgil_downbeat': 0.437837346187323,
  'CMLt_downbeat': 0.16705336426914152,
  'AMLt_downbeat': 0.3284823284823285},
 'asap/Chopin_Ballades_4_Levitsky18M/track.npy': {'F-measure_beat': 0.6887192536047498,
  'Cemgil_beat': 0.5969599417731178,
  'CMLt_beat': 0.38483547925608014,
  'AMLt_beat': 0.38483547925608014,
  'F-measure_downbeat': 0.531055900621118,
  'Cemgil_downbeat': 0.46593061650245543,
  'CMLt_downbeat': 0.14603960396039603,
  'AMLt_downbeat': 0.3068893528183716},
 'asap/Chopin_Ballades_4_LuEric04M/track.npy': {'F-measure_beat': 0.6666666666666666,
  'Cemgil_beat': 0.5603148697160893,
  'CMLt_beat': 0.36270753512132825,
  'AMLt_beat': 0.36270753512132825,
  'F-measure_downbeat': 0.5587301587301587,
  'Cemgil_downbeat': 0.4688296104245795,
  'CMLt_downbeat': 0.21794871794871795,
  'AMLt_downbeat': 0.2630480167014614},
 'asap/Chopin_Ballades_4_MiyashitaM04M/track.npy': {'F-measure_beat': 0.6873977086743045,
  'Cemgil_beat': 0.5872708545290796,
  'CMLt_beat': 0.3935309973045822,
  'AMLt_beat': 0.3935309973045822,
  'F-measure_downbeat': 0.5481239804241435,
  'Cemgil_downbeat': 0.45473239817058436,
  'CMLt_downbeat': 0.225201072386059,
  'AMLt_downbeat': 0.24843423799582465},
 'asap/Chopin_Ballades_4_Mizumoto02M/track.npy': {'F-measure_beat': 0.666130329847144,
  'Cemgil_beat': 0.5697646795657831,
  'CMLt_beat': 0.381389252948886,
  'AMLt_beat': 0.381389252948886,
  'F-measure_downbeat': 0.5015197568389057,
  'Cemgil_downbeat': 0.4339973031860291,
  'CMLt_downbeat': 0.1722488038277512,
  'AMLt_downbeat': 0.22964509394572025},
 'asap/Chopin_Ballades_4_Nikiforov13M/track.npy': {'F-measure_beat': 0.5995558845299779,
  'Cemgil_beat': 0.5210940738682762,
  'CMLt_beat': 0.28243398392652125,
  'AMLt_beat': 0.28243398392652125,
  'F-measure_downbeat': 0.5,
  'Cemgil_downbeat': 0.44063387107775226,
  'CMLt_downbeat': 0.09913793103448276,
  'AMLt_downbeat': 0.38413361169102295},
 'asap/Chopin_Etudes_op_25_11_KimSuyeon03M/track.npy': {'F-measure_beat': 0.8025157232704403,
  'Cemgil_beat': 0.6802326868325984,
  'CMLt_beat': 0.548926014319809,
  'AMLt_beat': 0.548926014319809,
  'F-measure_downbeat': 0.6666666666666667,
  'Cemgil_downbeat': 0.6022700563809089,
  'CMLt_downbeat': 0.18235294117647058,
  'AMLt_downbeat': 0.5561497326203209},
 'asap/Chopin_Etudes_op_25_11_KyykhynenT10M/track.npy': {'F-measure_beat': 0.8988476312419974,
  'Cemgil_beat': 0.7703476364518584,
  'CMLt_beat': 0.7772277227722773,
  'AMLt_beat': 0.7772277227722773,
  'F-measure_downbeat': 0.6228373702422145,
  'Cemgil_downbeat': 0.6534671761829686,
  'CMLt_downbeat': 0.020618556701030927,
  'AMLt_downbeat': 0.8092783505154639},
 'asap/Chopin_Etudes_op_25_11_Lisiecki07M/track.npy': {'F-measure_beat': 0.8308080808080809,
  'Cemgil_beat': 0.725707197997676,
  'CMLt_beat': 0.7004830917874396,
  'AMLt_beat': 0.7004830917874396,
  'F-measure_downbeat': 0.5612903225806452,
  'Cemgil_downbeat': 0.552662369476626,
  'CMLt_downbeat': 0.046511627906976744,
  'AMLt_downbeat': 0.5953488372093023},
 'asap/Chopin_Etudes_op_25_11_MiyashitaM03M/track.npy': {'F-measure_beat': 0.7915273132664438,
  'Cemgil_beat': 0.6911269553695863,
  'CMLt_beat': 0.5230769230769231,
  'AMLt_beat': 0.5230769230769231,
  'F-measure_downbeat': 0.5517241379310346,
  'Cemgil_downbeat': 0.5905804018377463,
  'CMLt_downbeat': 0.0,
  'AMLt_downbeat': 0.7142857142857143},
 'asap/Chopin_Etudes_op_25_11_Richardson_2013_08M/track.npy': {'F-measure_beat': 0.8957816377171216,
  'Cemgil_beat': 0.7857670137709816,
  'CMLt_beat': 0.7645687645687645,
  'AMLt_beat': 0.7645687645687645,
  'F-measure_downbeat': 0.7165354330708661,
  'Cemgil_downbeat': 0.6414679190737209,
  'CMLt_downbeat': 0.27044025157232704,
  'AMLt_downbeat': 0.455026455026455},
 'asap/Chopin_Etudes_op_25_11_Richardson_2015_03M/track.npy': {'F-measure_beat': 0.8501742160278747,
  'Cemgil_beat': 0.7412007154855255,
  'CMLt_beat': 0.6012396694214877,
  'AMLt_beat': 0.6012396694214877,
  'F-measure_downbeat': 0.5714285714285714,
  'Cemgil_downbeat': 0.6048361222976603,
  'CMLt_downbeat': 0.0,
  'AMLt_downbeat': 0.7136563876651982},
 'asap/Chopin_Etudes_op_25_11_Sham02M/track.npy': {'F-measure_beat': 0.8828828828828829,
  'Cemgil_beat': 0.7551311310184401,
  'CMLt_beat': 0.7694235588972431,
  'AMLt_beat': 0.7694235588972431,
  'F-measure_downbeat': 0.6341463414634145,
  'Cemgil_downbeat': 0.6172233016842419,
  'CMLt_downbeat': 0.078125,
  'AMLt_downbeat': 0.7291666666666666},
 'asap/Chopin_Etudes_op_25_11_Shychko03M/track.npy': {'F-measure_beat': 0.8065326633165829,
  'Cemgil_beat': 0.6865760537869648,
  'CMLt_beat': 0.5952380952380952,
  'AMLt_beat': 0.5952380952380952,
  'F-measure_downbeat': 0.6423357664233577,
  'Cemgil_downbeat': 0.6014041335442564,
  'CMLt_downbeat': 0.12222222222222222,
  'AMLt_downbeat': 0.6844919786096256},
 'asap/Chopin_Etudes_op_25_11_Song02M/track.npy': {'F-measure_beat': 0.8408826945412311,
  'Cemgil_beat': 0.7354863047911806,
  'CMLt_beat': 0.6004140786749482,
  'AMLt_beat': 0.6004140786749482,
  'F-measure_downbeat': 0.5766871165644172,
  'Cemgil_downbeat': 0.5911867175224197,
  'CMLt_downbeat': 0.017316017316017316,
  'AMLt_downbeat': 0.6753246753246753},
 'asap/Chopin_Etudes_op_25_11_WangA02M/track.npy': {'F-measure_beat': 0.7856341189674522,
  'Cemgil_beat': 0.6672738618263726,
  'CMLt_beat': 0.49612403100775193,
  'AMLt_beat': 0.49612403100775193,
  'F-measure_downbeat': 0.5432835820895522,
  'Cemgil_downbeat': 0.5772183789117366,
  'CMLt_downbeat': 0.004149377593360996,
  'AMLt_downbeat': 0.6556016597510373},
 'asap/Chopin_Etudes_op_25_1_LeeN03M/track.npy': {'F-measure_beat': 0.5118219749652295,
  'Cemgil_beat': 0.5134157956523107,
  'CMLt_beat': 0.0018796992481203006,
  'AMLt_beat': 0.34962406015037595,
  'F-measure_downbeat': 0.338235294117647,
  'Cemgil_downbeat': 0.33421085025054076,
  'CMLt_downbeat': 0.0,
  'AMLt_downbeat': 0.0044444444444444444},
 'asap/Chopin_Etudes_op_25_1_TongB02M/track.npy': {'F-measure_beat': 0.5818181818181818,
  'Cemgil_beat': 0.4885204992623039,
  'CMLt_beat': 0.1674641148325359,
  'AMLt_beat': 0.20334928229665072,
  'F-measure_downbeat': 0.380952380952381,
  'Cemgil_downbeat': 0.3433632932480133,
  'CMLt_downbeat': 0.0,
  'AMLt_downbeat': 0.16847826086956522},
 'asap/Chopin_Etudes_op_25_1_TuanS04M/track.npy': {'F-measure_beat': 0.584717607973422,
  'Cemgil_beat': 0.5368075223979667,
  'CMLt_beat': 0.0963855421686747,